language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: OQsQWLwAUmaKVOVgFp+MN+KGJmHfmyGn/ypAd5+IwbLnAD32fW49CPVQ/X3fZ5KKS6x3QUdMuYCbVIttG3rs8AsrhfHb6OJLYTk8k0yy2/OBIIx15Cac5iZcgpX8ji5G/gW1Gt8z+DIPnsxSQbXL+TFn5Aj3XuvPTkKMd/Ls3kgpN31zds58kqy10mD2zwdzQ1vVeKe+/E124vWZ/5bXcNztM40FI2VWgnaO9tXG0Vr8TiH2sWuiChiLAJjTbvsI0B8C8u1BK0zn8ASSliuAEp36XLcNFdOY4hAgEMSFGzQJl0Cin3Bs9pSuvF1hpHahf924qhrF1EKovT5EKoa0ma5U1qe/sGrBkIW3Rn6trXSKMA4D89hcqHDZ900NM3PBKWYQ78iGr/vvdAPTix89Yz3UE0TBuyvJjdpMs1jv+vD577pCiwcpLbecoE0/7nAx7AF1MLpKIinp6znykyfMdeTE955McfU79+7bhZjmwThwMzeXh6FsNHuG+lLVZmr0LHCQca1az00gtEH4mnZIkewR1kL2E78wVSv/nW4+YXpq8Zy/5E25Ru16lgbpd9Hky1lg8LqUQv6xYsdmdWmy0CVSPnr2P2cHQmpvcj+QWyxgjEFDRcDeGW0srT7LLVcNUyYAIbU3gYP1WkxaXQR5XnPkXChdrfl6lYdXtjgwKZg=
  - secure: qZqsWoF8qLL4Paq2jJWFSF5OHehsVz9XfkSxcY7izPzJTVsQCD1pMwxlLwVLyKEtwOw52PSzSMQTjP4lp4Fhlb9RFyqaseUMFVA+R5IGLlEX2xrJmCCiR/f2duupITPxVf81TaoWeZK+HkzOO32ekraUur0MRa4LJ777d8OT6BI5KfbcH8MhTi+SLs/6Td7L2Nq1stVd2ive+8MPUIuUd5xRYDQlmm9Tce4McwkeCBv563GPGCucixe2iHA9VOIRm08DkFzn330+NwjIEL+VyGX4ppKq42Pz3UKBLhMOHECPb089uYKvl+zfQ8mt2sQ2pc5C02nCj/dVRyJqAIVMYRQ+ArFq2R+Bpwnj9m8IF0u4Ggf4Hp4B4NM2qC+RZiHHGyMTpfR44IdUwp63wWQWGHws68Q5UWMjW3b/lVAWfIJ6kDAinc1XHbnVmwBX+yTGO2mn4OEiR6nBschX4ZEN0iyZA/qvvnh/iHD1a5BcSetVeFGD3g3BjTtGxr/xIMJ90OlRRy7+ZuC+3QC23XUpe1I8bnyKNhC+QW345QYQh6haN5cO42ZEA2S6rmJFaO0PDRhLMSVioaInyBDwr2D6GQkDJC3aS9tVrgddiSZCw39ewIU04hxGx6CaqNS65PjfAOwIN+AOFXm/R65HRA/ZACtVCZAEjLQJ/+Pb6PSI2EY=
