language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: WR2d2WFG40xbcfaFY8wkg8Kklqsr3ioxl8nfRGR5ikrjDrjLz7WpYtdI9wZepYaGsaY0cafM7B1v4AdXhKAwteBODPzNvQemgX2HYd0778YhBU8WYhZaaZt+NaQwd2DjMnd3jJEqEXnDkXnfJq9oFtvgG0xEBkuEuyUCGfc4jI6x8T8/43dfL5xwmIRq1SfPCYEROI2RrdFhscWaYM9i7NPjLsmU81IQy+XdLhc+Hj6whZuVA9pYkfbAqeUM5P9LH3kRsJ2vKc6Rldxm+A8qJJSb7KHK8IqWuVwXXW4sw8fI6zmqfDc7bdeVQi4cVt+weDaf7UkhG9QUateLMPWe1gv4i/x0Cr45GNfQw0Bslfu2tuAvgB115NxnrX5z4+OaOT8/Rb5kwZU/IzK27KL13csOfwLduYp32O9MXEUoJSJZwSenNoYKqZUXCOk1eLT4EeJHDfJeC5laWVX2dPbluXTJCG/rGAE0yk+13R2+Jrxi//DdmPjyePltdZq7PoV4n13ReReqr4t9BousSahLi4X1U0p3C/aJoGTjIXYj0WtvQtfx6VffBp+yxlNrdIeh0KpVg/fqo/IzLQ+i6uwNPbst9kLPqXx1MEdqs2QmbGoDYorcBIDcftB8EtVxncnt9ETyJH4yJb32CmaaY8nSVG51cz+45EU6vjCh/TdMwOg=
  secret_access_key:
    secure: ayOr3/g1Qh8horhbwkOFvUVWhKSpclRYxUlrpk27S+bim2kpO8ozfwgvPEjg+7O7iJNaNCj+gBaXqi7MbpFHpiRa2agtOAA4uw3mQluhHyiEXaeX7BM0djhCcgHNLJuDbbwxw3tRL/CFcTcJWdDvatlMs/Os7brJlCeGI34TBH13q/nOCiShjL0OhNYWuAsH4CDJpohNAdm8xDR8nof+0V9oeSyZfGDs9Isibjj9sPi8HXiyr71Gbxxt4J048B/2Wref+bIhg1tvkwU/XMgvdLhP/7R6kuTJcTtuRO1zvG+UhuD3ZebhX9GA3rntiFg4fCS+7Z2aE5nm3BQkHiM6o8nDtrKzy7y9K2xgEHLoOrM2GhffiqHZUxa6ylIi6Icyk9zdN0Qq1r8cndQRIKggGgPy38+gg+3GsZ4Roz+IthU70cZZ52IXZst41OW99ILzrR8alo/ZOPDTfQuzx8sOipRCJgY9ApdQcBrPx9Gm1j0PsKaaWJneWTqjIpC6PqZbC37Ilp+RmwMW3tTI+MRu4ebtsNvTW+qVkzinUEEiVj9fe4zwNI2OWDhTOhukq3enQuac+8CKasdu4iyxBvfwj/+afcWZ72XsAb2WfyO3pW19EFC4Af+uHiDLRydrE9DlPZrfYRFC/ZLvTTCRWFMZgwXNJ49KVA6KMfQsqpX9E84=
  bucket: dd-sketch-website
  skip_cleanup: true
  acl: public_read
  local_dir: public
