language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: DAJqwZ1/n1Tz1qVSVzyYAStzMNHcEfCISVFUFnZEjNOlvz12dDfgbPSPzm0U3ta5inpM+7Eg+d47IxwK2j0I5qikd15bPIMND5e7NBeKX5uzhzCM2K0CN3jvEfWomJ+wR6FLUzdj8ClmEYL2QNxdzqPy5nPk1gdFbPy/XA2nnbrL2xPpGr6IBgdKSu3pyjHlmiAqwftZIbyN1px7J441+/Uj/nYZYmjcyqLfrS5+dqmQk4dN+hLoGphxztw/dNiXbPxashrzMUK5lcRcfkC6TfQYZ7Fxi6kzzQAvKe7mTXb57AzTMOaSpCfrsMpvmw+xFuLERnGC4erHvNtT7+6DAo75kNguoLvcq5lYnOFmUtAyb3vzWI8Pz3PlfG9uk79X5UVsCxIDHlmVsZ1tC/5NMZvEZZWo4mGy6UusONaXlIrC7swjTjMmKF5/gJgmt/qtJWHdTu/6xiIk5TBiYsDC/7UCbX03WTEVMEzQeXSnZF8Slve8k0c+WGftQZeyAJG/nsc+K62Ku09bH/FLDyRiAj0d+Rbss87tFretnz9705J1zp2AatLs/Z2nuTm5t63hziXbGM8jfWA7JjCfYJAk+wkifyj9C97YxFVH14M+/GFaE9ZrnVx9iYZwc0+NQr6a9r9TKdoPLwG3iRVdHhiBQ2niJqKFQfkE3LvGIgijvSc=
  - secure: f37LR4oP/d7zdFhz72oaHMtRp7f03nFtu9IhXnGy39rJVXVw00l6b7lU7FPe/QwaeD5AsNCdIU7pp8xiGGmzTIlLAUs/xQx+rPRbZqL36HrLl8AOxy0eQOACpqJG4rQK9Eyb0YMtDJb1UBsqtmvHh70IahzJk9TL451aZm+6E3Udl/X0ynBJfz9dBb7T0pQSvLAXedW9XWtVvJJFsDYjHLx9/1LFIY0cozoZhr5Uo3ztPl3XCPHVzlU33NzNQYgwaEGe+fA28jZ1mpwWg+x2MAHOWC7OEnJHgtRaOD0fLOgWQ39FVJxcvfFPjTz/8PjZRb09Hr6qA8kQIC1WZHfbobiVm7XJBbX0HMWR35fSedJIaxCjxjC3e265Wafj1mlbJ6+OHUKijPcXiy2Bjl+W8vDArqNYgvLm1FSXZeyUonT/eDCqiBU8rRXpZSL/vlHGlRW6fuGDe4rM289wEa1LVMyFnz5dsrqERNcVxRQY86EFvX+nAAKG1uueYPfJsJaOLlekuLKeXG4f69lIBEHTiS2pRIIm31GSY+xFfZW/sqCUuGQFWammhrWQC0inA2elSNEoJfDuVg6+V5ZxWCtxrzfUqD5LNfX9y/thUrK1Co1GhjDiSExez/9k0J7gVYw+W6cM2egi834cQrBOO63tJZ1QKLyR/ZwMJpB/5arvV2U=
