language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: bPSLkkw5rNozGm7ilByGU2G2M5UyBrnM78097vqzCBubRE8ud0U1r86fhxzvFsbrxtbfwGqIkykzXzSMCi4imIy4322NaifM145UcXB4s6Q4uPLisdmvdWRQ3jxxJGiDykmqXfuQkqV2Hdi01WroZLiK0WxRPwyMXgCrjbLctbqMRPw79DdaCveAn+l8LqYDsdFEbtE4NtPtLwKJJWOnSqOBQhf3xnqQw3I/YeSxWGuAXlBHlatCyjtZEYqkdyjVS47NT3soC56L7s+SDjyn/VnRT4pn48OaM+ltm82Ejl36YJ0n7a1pruSOdotVU5sePqzyLnuP/JXb+ov+p6rkvYPnQJwkAmJPlZuGmPES/AzA3tYFHvCvHHliWXiso8z4Bp+h+ZbtkMPN650E0V9R/wMxgaGCpl3PaBT65KARcjqC2ZcIoYG/LvDelaCpJSFfndPj+a/zp8jREbWACok8VoD3b4ToGRuzx8Cy3L4SK28JvBxl1kDVcvspIo0V1Ci8eD05FA6sQuf1cIX5TJZdHs/ofoLXZhJYGT5mKM1+1dcFp4jxJ27q0wIdhtxenSpEuqUGClGH7vq/1D2qF9OiLgrq6nZ0ceyNvQEQ2WGEgk2soUjNddW4SuPOOLHUshC9y1rfqQxE+uUAisnTk+W+gSba0VGC9Bgwq5d1EAF7tek=
  - secure: bSEO9opUUWPPQB5YW1qhwiodvQPRsMu48CuZ05OpJQNIRWYNWL/tEYiAQGoNo2dsTCz17bevgv5X4rdp1l+mEv4VmPUmfloipNUBaa6jzG9SzwHxkqTqen6QoXlexzl7241hG6i4/LXd3pA01w3BfdJAWA9QIHe87kiO2f3c6Ar9LXuNB83GzTxM7CdOS2KoZdL3rrRZuvn+IhqU0yvCu1yDxTSABfpnzxFcp4nLX93d8Elnm1LOpGHzQS8U6baJ/dCQdPJL4wcrf9o2ctjTByflnCrwn0u3gRz2S1Q1q+IUvLgvsUCRjbntAhJ5pIp52YMroRqs3yo1y3aLnA66Vkvl69mi0Tt0ExcpjVSilg2It7ezQI5E5BwrnXPDykYs85bl02QRkofLK6SFYkbwl8bbujViLuA+FMQ6kYitIL+kSbKrBKxJgUJaeND0bwA7r3bDgpCc7Zdj9okN1Fhh1O4cZwr2tHQRyA3gcjX7k4ZksjY5WwnkwwG7l+QubqMqlRFHwHOdxoJ40Rkz8wcWO+Mz4JNkuMDoDY5Lgzw9bZ/SdjDt2yx8v6+5GNDUa7dTBRlWKPPJLK/yK0/yYHW1OL24aO/ht3iVxGlKTUUNwvSCc9mPYLqA0IgpgcFguPS3HBwMmgbJ8150rR81tEePSXQxZMdE9tCxXHh6OhUrqOM=
