language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: X2FI6c4iy2vwwOAInvJfTrOUgyTTK8x17+kQkokMk8+g9ECScBeAqY1p5CBKKAPakSe6Z1Fcw1xQ569m3ZwesDr9qDhWyphnUMcqE6RKaqxwqZGV6jaijBdlf7TSd6zQIBI7VXRQwXP70AVP7l0gxAqctc/qHC5d5jg9kShQEyiNn5ZqTTMJJQ7Rdsg/urjcxa7+v2jr/QnXljl0912bjQcDKhWUpt/kYjvXnnnMPAp1XTzEkqTqdTAtsfY72UwqhFdzHiUypfYY5MWwYDKmkzTAwwYmg9/wh/pKEDPOs/CGZTy4w/yp8L2/ZcEYig0EM57m/xUz0O1sq3ucJJ+Rr/C1NYss9mtW1eIjPADRr/UijGj/YnprRL4qeImNY09rs/RdzaNy0Ml6AHhrDV4RS6smJu2DKlolPf2XwiGUjYLEzawq83My6C3r4F1qenJBp7AI32NyvlEfODkw5eGtsq+SaHxHMWTCgPjtl5hyX1vd+lhd9kluYvVjNpBIDtQBYmJ0GYib067KcH6/XSdiaKdMVQT2mCjZS1RMWYje7pl/1wk+v3G66r2bTjkgCzglklcbVnr5pHGwHkXOYzlNiZOrWhsOdDLkBKEzm5BZRZrGfEPLzf0xKRHLgjQV3sYCuX/Sq9f/b8Ui2Hkc8ZsBMtpSxg1wZKePx/DzdQjmuqw=
  secret_access_key:
    secure: HLY6jmyiVvTHuTZbtbeKBlYmTVFeTjo9HIdCthJNbaRJ2mfBm3PJAA7e0QNyz8fGDcW9BSe+YyMVkkkqizbPgTAgLKMoKEq/k+ru5r8lROgv0q/yIwRHPnWWU5fhO9s2StuOrh2birbulCgUstXg8Uf+2UtFO6u5kdJW1GmrkPQiuB6JSKIsYBjReQnH57TGSHpy9xkD4dGAXM34cKtfZlqB7iRnz688kL0wK86sZtTZfGGOt/oEuzLsqKnD7lSIe0gjhcENNrmv9d4vW+ir6C6WAJYZD14YGhHG1/3RDcLDYTOpahasvSvhUgT6n9vNiVc8deb/P4XG1eH0987p26ZFXsg2nWo0fJaDNzC6AMehpKostrtZL5fzjN+fn35oQiLTfEyQrGqzDp6nL2EWZbpuf0T+tqeG/5Kym0Up5fseaGKjEELglkqy9XM1hG84r6k9Y02VYHqbupZki2+GYz6+Jt/++W93Tji+H6AEtsldVks/CyJh+7vEeNYoUQ+KibgBX4BlYONYnvfWe5x/4+yNgeFs2u9yPltsJvy2cCPOe8Xa4lPPaukPVcYgX9avaAOzi9aIb6DSOyBm6roS2n0adtXdvv3nqDVWgUlSGCQdlDr9UZlE3WYGNDiHdLWn6ZzU7kg0sjewq1d25zozTT7G1hzZiY/QtmAWWKarLl8=
  bucket: dd-sketch-website
  skip_cleanup: true
  acl: public_read
  local_dir: public
